### PR TITLE
added a check that type array must have items

### PR DESCRIPTION
**Pull request by kreamyx**
This PR checks that an object of type array must have an items key

### CODE REVIEW

**Comment by sttts** [comment]
Why this check?

**Comment by sttts** [comment]
I believe this is a misunderstanding of https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object:

```
items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.
```

This says something about the value in the spec (i.e. meta level), not about the validated values.

**Comment by casualjim** [comment]
We had several issues reported where it always turned out to be the same bug. 
But if this validation is used for a more generic json schema that check is wrong, I agree.

Maybe we should make this this configurable?

**Comment by fredbi** [comment]
In don't think we have to. We have to separate the json-schema validation logics from the swagger-schema.
Basically, what we need to overcome this is to extend current schema validator to build a swagger-schema validator and add there all additional swagger-specific constraints: arrays must have items, default must validate schema, example should validate schema

**Comment by fredbi** [comment]
What is true is that this PR added a bug we have been living with for quite some time.

**Comment by nikhita** [comment]
```
items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.
```

This is from https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object.

> items MUST be present if the type is array.

From this, my understanding is:

- if the `type` is `array`, then `items` must be present.
- if `items` is present, it is _not_ necessary that `type` should be present.

One of the bugs we hit in Kubernetes (https://github.com/kubernetes/kubernetes/issues/68466) is that the `items` keyword needs to be always paired up with a `type`. This check was not introduced in this PR, but in https://github.com/go-openapi/validate/pull/37.

Would you consider it acceptable to remove this check? This should be backward compatible too.

**Comment by casualjim** [comment]
@nikhita feel free to send a PR. I do think we need both kind of nuances.

I don't think we should wait until somebody finds the time to separate out the pure json schema implementation from these repos. It's easier to just provide a config that allows us to  have different behavior when validating schemas vs validation a swagger spec.

The only problem I have is that I have no time to work on this atm. So if somebody else could pick this up that'd be great.

**Comment by nikhita** [comment]
>  It's easier to just provide a config that allows us to have different behavior when validating schemas vs validation a swagger spec.

Would this mean adding a field to make it configurable here:

https://github.com/go-openapi/validate/blob/e0648ff405079d973622f8b2bf739ed3a1c5cd9b/schema.go#L35-L42

If so, that would include adding an argument/option to:

https://github.com/go-openapi/validate/blob/e0648ff405079d973622f8b2bf739ed3a1c5cd9b/schema.go#L58

That would be a breaking change to `NewSchemaValidator`, wouldn't it? Is that ok?

**Comment by casualjim** [comment]
I think we can introduce the functional options pattern and use a varargs of ...Option like so:

```go
type Option func(*SchemaValidator)

func NewSchemaValidator(schema *spec.Schema, rootSchema interface{}, root string, formats strfmt.Registry, options ...Option) *SchemaValidator
```

That should allow us to make the change without introducing breaking behavior and retaining just one entry point method for validating a schema

**Pull request merged**
