### PR TITLE
fix: *string(nil) not equal &string

### PR DESCRIPTION
**Pull request by jiuker**
fix: *string(nil) not equal &string("")

```go
func TestRequired(t *testing.T) {
	empty := ""
	a := struct {
		A *string
	}{
		A: &empty,
	}
	t.Log(Required("A", "a", a.A))
	t.Log(BeforeRequired("A", "a", a.A))
}
```
```log
=== RUN   TestRequired
    require_test.go:14: A in a is required
    require_test.go:15: <nil>
--- PASS: TestRequired (0.00s)
PASS
```

### CODE REVIEW

**Comment by youyuanwu** [comment]
Can you add the test case in the test file?

**Comment by jiuker** [comment]
@youyuanwu I put the UT now. Reivew plz.

**Comment by jiuker** [comment]
@youyuanwu Looks like workflow failed. But it doesn't feel like it has anything to do with the pr I submitted.

**Comment by youyuanwu** [comment]
Master branch ci is working now. go version is updated as well. You can rebase.

**Comment by jiuker** [comment]
@youyuanwu cc

**Comment by jiuker** [comment]
@casualjim will I do more tests for code cover?

**Review by youyuanwu — APPROVED** [review]

**Comment by wawaka** [comment]
this should be reverted as it breaks validation completely @youyuanwu

**Pull request merged**
