### PR TITLE
Recognize path parameters in path segment fragments #39

### PR DESCRIPTION
**Pull request by elakito**
PR for #39

### CODE REVIEW

**Comment by casualjim** [comment]
I am not sure if this is supported for openapi 2.0 spec

**Comment by elakito** [comment]
Hi @casualjim, thank you for looking into this. I don't find the Open-API 2.0 spec explicitly allowing this URI template usage but neither forbidding this usage of URI templates. There is a related ticket about this URI template usage at OAP/OpenAPI-Specification where Ron mentioned that the spec itself does not forbid this usage.
https://github.com/OAI/OpenAPI-Specification/issues/1248
regards, aki

**Comment by casualjim** [comment]
ok, but making this work for just validation might not be enough, are you planning on also sending a PR to the runtime to support this in the router?

**Comment by elakito** [comment]
Yes. i'll make the corresponding change to the server side and create a PR.
thanks.

**Comment by elakito** [comment]
Hi @casualjim,
Initially, I thought we had to modify the denco code so that the parameters are matched and extracted from that layer. But upon looking in it more, it would be better to not change the denco code but pass a different url template from go-openapi (i.e., just one param per segment) to let it match and extract the entire segment from the denco layer, and do the actual parameter matching using this extracted string against the real parameters. There is a limitation in this approach (i.e., there is no backtracking once matched but if that is required, the denco code will need to be modified in an incompatible way, which we can avoid for now).

By the way, without this change in go-openapi/runtime, the client side code already works fine and also the server side code if there is one parameter per segment e.g.
/foo/lis{fragment}

So maybe, you could merge this PR into validation and I can open an issue in runtime to track this more-than one param per segment at the server side issue?

regards, aki

**Comment by casualjim** [comment]
@elakito 🥇 thanks

**Pull request merged**
