### PR TITLE
Use swag.File instead of runtime.File

### PR DESCRIPTION
**Pull request by kzys**
While runtime.File will be defined as an alias, that won't be seen in
the run-time, so reflection need to use swag.File instead.

https://github.com/go-openapi/validate/issues/143

Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>

### CODE REVIEW

**Comment by kzys** [comment]
Hmm, not so sure why Travis is still there. Do we need to disable that from Travis' website?

**Review by youyuanwu — APPROVED** [review]

**Comment by youyuanwu** [comment]
Close and reopen to see travis ci goes away.

**Comment by youyuanwu** [comment]
Deleted travis web hook. Close and reopen again.

**Comment by youyuanwu** [comment]
Removed the travis branch protection in settings. Travis ci is finally gone.

**Pull request merged**
