### PR TITLE
Remove stray .orig file

### PR DESCRIPTION
**Pull request by mkkuba**
Remove stray `.orig` file

### CODE REVIEW

**Comment by fredbi** [comment]
Why do you this this is stray?

**Comment by mkkuba** [comment]
> Why do you think this is stray?

Apologies if that is not the case!  I thought this was an orphan file from a `git merge`

**Comment by fredbi** [comment]
Well I am not saying this is really useful, but as far as I remember this was a copy of the original jsonSchema testcase just to have it at hand.

**Comment by mkkuba** [comment]
I see, I will close this PR then.

**Pull request closed without merging**
